version: '3'

services: 
    connect1:
        image: llamasarethebest/kafka-connect
        container_name: kafka_connect1
        ports:
            - "8083:8083"
        environment: 
            KAFKA_BOOTSTRAP_SERVERS: <ip-address>:<port>,<ip-address2>:<port2>
            KAFKA_GROUP_ID: connect-cluster
            KAFKA_PLUGIN_PATH: /opt/connectors
            KAFKA_STATUS_STORAGE_PARTITIONS: 2
            KAFKA_STATUS_STORAGE_REPLICATION_FACTOR: 3
        volumes: 
            - .\connectors:/opt/connectors:ro